version: "3"
services:
  nodejs_docker:
    # Define configuration for building the nodejs_docker 'service' container.
    build:
      context: .
      dockerfile: Dockerfile
    # This works with 'build' to create image, if not existing, to build new image from 'build' config.
    # If 'build' is not present, will try and pull an image with the specified name.
    # See https://docs.docker.com/compose/compose-file/#image 
    image: alexsansom/nodejs_docker
    # Specifying a container_name stops ability to use more than one of a contianer at a time as each container needs to have unique name.
    #container_name: nodejs_docker
    # Map host (the Mac) port to port that's EXPOSEd in the Dockerfile.
    ports:
      - 3000:3000
    # Mount a host (the Mac) filesystem path to a container path (which is used, for this example, as the WORKDIR in the Dockerfile).
    # This is being defined at this 'service' level, but can be defined at top level, for use across other services.
    volumes:
      - .:/app
